Pass -c since Ubuntu has a newer reprotest
Failed before with:

> ValueError: unrecognised file type: "./release.sh"; try giving an appropriate --build-command